### ISSUE TITLE
P2P peer selection first milestone

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/ouroboros-network#1306]
The goal for the first demonstration of the peer selection for peer-to-peer graph construction is to have a small number of nodes connected to an existing network (e.g. mainnet) and for them to discover and connect to each other.

The technical goals are:
- [x] p2p governor with basic QC tests
- [x] design to cover both federated and distributed cases, to allow early integration
- [x] DNS based provider for finding existing federated peers
- [ ] gossip protocol
- [ ] integration with existing code for establishing and monitoring connections
- [x] initial simulation framework to evaluate quality of graph construction

**Comment by dcoutts** [comment]
The code is now included, and is tested pretty thoroughly in isolation, but not yet integrated with the rest of the system.

Some remaining things to do for future milestones:
- [ ] complete testing with simulated connection failures and hot -> warm demotion
- [ ] decide how to handle connection backoff with failures that occur shortly after connecting, to avoid reconnect loop
- [ ] integration for federated setting (using the DNS provider of public root peers)
