### ISSUE TITLE
Connection Manager

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#1473]
Implementation of connection management component.
* [x] - connection manager spec: #2756
* [x] - connection manager
* [x] - `KeepAlive` protocol: #2175 
* [x] - `WarmPeer` protocol: #2210 
* [x] - server: #2213
* [x] - integration with peer-to-peer governor: #2214 
* [x] - on demand bidirectional mux: #1731, #2166 
* [x] - mux's trailing data: #2205
* [x] - backport dns fixes #2311
* [x] - integration with diffusion layer #2313
* [x] - integration with `cardano-node`.

**Comment by avieth** [comment]
Implementation is here https://github.com/input-output-hk/ouroboros-network/pull/1455

Currently working on integration with lazy mux.
