### ISSUE TITLE
Chain DB: q-s-m tests

### ISSUE THREAD

**Issue by edsko** [input-output-hk/ouroboros-network#246]

**Comment by mrBliss** [comment]
#617 will include q-s-m tests. These tests will probably not cover all edge cases, but the most important bits.  Additionally, as the consensus tests use the ChainDB, most functionality that is actually used in practice will be tested by the consensus tests already. Thus, extensive testing won't be necessary until the public testnet or even mainnet.

**Comment by mrBliss** [comment]
Tasks:
- [ ] Labelling
- [ ] Shrinking
- [ ] #625 Test with invalid blocks
- [ ] #653 Test with corruption
- [ ] Test with invalid iterator bounds
- [ ] Test with EBBs

**Comment by mrBliss** [comment]
- [ ] Test with corruption: #653
- [ ] Test with invalid blocks: #625 
- [ ] Labelling
- [ ] Shrinking
- [ ] Test with invalid iterator bounds
- [ ] Test with EBBs and check that they are handled correctly by iterators, readers, `getBlock`, etc.
- [ ] Coverage checking
