### ISSUE TITLE
P2P - Block Producer

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3887]
# Objective

Enable _Stake-Driven Peer Discovery with Robust Peer Selection_ (aka P2P) on block producers

* [x] input-output-hk/ouroboros-network#3159
* [x] input-output-hk/ouroboros-network#3907
* [x] input-output-hk/cardano-api#45
* [x] input-output-hk/ouroboros-consensus#140
* [x] input-output-hk/cardano-node#5383 (input-output-hk/cardano-node#4024) 
* [x] analyse performance regression of BPs when P2P is enabled (possibly fixed by input-output-hk/ouroboros-network#4620)

# Risks

The P2P release was split to contain the risk of releasing major changes in the network component.

# Dependencies

We ought to be able to analyse how many P2P relays are already deployed on the network:
*  input-output-hk/ouroboros-network#3938
_This is no longer a dependency because CF is able to track that information._
