### ISSUE TITLE
P2P - Daedalus release

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3969]
This epic collects all issues which have to be solved before releasing Daedalus with P2P enabled nodes.

# Dependencies

* [x] input-output-hk/ouroboros-network#3968
* [x] input-output-hk/ouroboros-network#4530
* [x] https://github.com/input-output-hk/ouroboros-network/issues/4615
* [x] IntersectMBO/ouroboros-network#4490
* [ ] **Genesis** requirement for _Daedalus_
