### ISSUE TITLE
Make a list of packages that can be factored out into separate libraries

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4070]
As part of our efforts to foster collaboration, we should look for parts of consensus that can be extracted as separate packages. Examples of this might include:

- [x] SOP strict: input-output-hk/ouroboros-consensus#554.
- [x] HasFS testing suite: input-output-hk/ouroboros-network#4082.
- [x] The [`ResourceRegistry`](https://input-output-hk.github.io/ouroboros-network/ouroboros-consensus/Ouroboros-Consensus-Util-ResourceRegistry.html): input-output-hk/ouroboros-consensus#553
- [ ] input-output-hk/ouroboros-network#4093 

We should create separate issues for each of the potential new packages we identify, and clarify that to close one such issue we need to announce the package in a blog-post.

**Comment by dnadales** [comment]
Maybe this one? https://github.com/input-output-hk/ouroboros-network/issues/3953 (modulo writing the library that generalizes QC combinators).

**Comment by Jasagredo** [comment]
I guess also this one:
- [ ] #4093

**Comment by dnadales** [comment]
Thanks, I'll edit.
