### ISSUE TITLE
Remaining UTxO-HD tasks for `v0.1-ready`

### ISSUE THREAD

**Issue by Jasagredo** [input-output-hk/ouroboros-network#4457]
I'm writing this as a logbook on the pending items.

# Prototype cleanup

These PRs can/should be reviewed and the comments found there be addressed.

I have used `graphite.dev` to manage this stack of PRs, it probably comes in handy in case someone picks this up.

* master
  * **PR #4352** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4352" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4341** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4341" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4342** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4342" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4343** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4343" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4316** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4316" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4366** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4344** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4344" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #4363** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #4391** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4391" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #4417** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4417" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #4424** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4424" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #4449** <a href="https://app.graphite.dev/github/pr/input-output-hk/ouroboros-network/4449" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

# Big changes
- [ ] #4393 
- [ ] #4444 Note that the NTC TxSubmission works on a tx-by-tx basis, so maybe this is not worth? Also it will clash with Duncan's pr for the mempool fairness.

# Small must-do changes
- Public API
    - [ ] #4402
    - [ ] #4401
    - [ ] #4373 
- Internal
    - [ ] #4394 The way this module works has to be improved. Using newtypes for before and after? Better combinators?

# Tech-debt maybe-do items
- Tests
    - [ ] #4455 
    - [ ] #4456 has to be investigated, perhaps it is not possible
    - [ ] #4228 
- Logic
    - [ ] #4446 not sure if we want to do it. We have to check if it will introduce too many dead-code paths (as the error case is impossible in absence of Consensus bugs)
    - [ ] #4367 
    - [ ] #4371 
    - [ ] #4407 
- Docs
    - [ ] #4392 
    - [ ] #4445 A couple of diagrams explaining how this works would be nice. Explain why it has to be an automorphism (Telescope.expand requires it)
    - [ ] #4398
