### ISSUE TITLE
UTxO-HD tech-debt maybe-do items

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/ouroboros-network#4486]
- Tests
    - [ ] #4455 
    - [ ] #4456 has to be investigated, perhaps it is not possible
    - [ ] #4228 
    - [ ] #4464 
    - [ ] #4055 
- Logic
    - [ ] #4446 not sure if we want to do it. We have to check if it will introduce too many dead-code paths (as the error case is impossible in absence of Consensus bugs)
    - [ ] #4367 
    - [ ] #4371 
    - [ ] #4407 
    - [ ] #4463 
- Docs
    - [ ] #4392 
    - [ ] #4445 A couple of diagrams explaining how this works would be nice. Explain why it has to be an automorphism (Telescope.expand requires it)
    - [ ] #4398 
    - [x] #4314 
- Potential performance improvements
    - [ ] https://github.com/input-output-hk/ouroboros-network/pull/4436/files
