### ISSUE TITLE
Transaction Submission Mini Protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#60]
__net_impl_protocol_tx_submission__
Implement the mini-protocol for transaction submission (in sim)

This only has to cover transaction submission for the federated case initially. It can rely on the assumption that if B gets blocks from A, then B can submit transactions to A. This work package does not cover end to end transaction relay, just the point-to-point submission protocol.

Testing the mini protocol in isolation should cover multiple integration levels:
- [x] direct,
- [x] via typed `Peer` with `connect`
- [x] via typed `PeerSender` with `connectPipelined`
- [x] codec tests,
- [x] via message channel,
- [x] via byte channel (with codec),
- [x] via local pipe

**Comment by coot** [comment]
PR #329
