### ISSUE TITLE
Chain Synchronization Mini Protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#61]
__net_impl_protocol_chain_sync__
Implement the mini-protocol for chain header synchronisation (in sim).

This is the application level protocol for continuously syncronising a chain of headers from one peer to another peer.

There have been several iteration of this protocol, along with interations in the framework for expressing all the "mini" protocols. The completion criteria for this work package is that

- [x] we have the protocol expressed in a satisfactory framework
- [x] tests in simulation that it can continuously synchronise a changing chain
- [x] including basic binary encoding to/from a byte level channel
- [x] it is used in working tests in the consensus layer

Testing the mini protocol in isolation should cover multiple integration levels:
- [x] direct,
- [x] via typed `Peer` with `connect`
- [x] codec tests
- [x] via message channel,
- [x] via byte channel (with codec),
5. via local pipe

**Comment by coot** [comment]
#10 #30

**Comment by coot** [comment]
@avieth PR with typed transitions protocol:
- #10 typed transitions
- #30 (incorporated into #10), including typed ping pong protocol
- #82 untyped transitions
- #54 `ChainSync` protocol termination
- #52 typed request / response miniprotocol
- #94 typed codec

**Comment by dcoutts** [comment]
Prior iterations of the chain sync protocol satisfy all the test criera above however we have concluded that we should use the typed framework for expressing this and all other mini protocols.

We will declare this work package done when the new iteration of the protocol in the typed framework passes all the tests and is in use in the consensus layer.
