### ISSUE TITLE
Block Download Mini Protocol

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#62]
__net_impl_protocol_block_download__
Implement the mini-protocol for block body download (in sim)

This is the application level protocol for fetching ranges of blocks from another peer.

Ultimately this is a relatively simple protocol, however the final design of this protocol must be informed by the block fetching logic. See #66. Its expression relies on the framework for expressing mini-protocols. See #61.

The completion criteria for this work package is that:

- [x] it has an interface that is deemed satisfactory for use by the block fetch logic. This relies on PoC work on the block fetch logic.
- [x] tests in simulation that it can correctly fetch ranges of a chain, and correctly reports failure on ranges not in the current chain
- [x] tests in simulation that multiple requests can be outstanding at once

Testing the mini protocol in isolation should cover multiple integration levels.

This epic is split into 3 tasks:
* #123 - block download protocol together with integration tests:
 - [x] direct,
 - [x] via typed `Peer` with `connect`
* #124 - codec for block download protocol messages, including coherence tests for that codec
* #125 - add more integration tests:
 - [x] codec in simulation
 - [x] via local pipe

**Comment by coot** [comment]
#50 - streaming in sim
#31 - typed streaming (no latency hiding)
#52 - typed request / response protocol

**Comment by coot** [comment]
PR #319 - block fetch mini protocol using typed-protocols
