### ISSUE TITLE
Multiplexing Protocols

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#65]
__net_impl_multiplexing_protocols__
Integrate and test the various protocols with the multiplexing, serialisation in simulation

This involves getting all the existing mini-protocols running together over the multiplexing mechanism either in simulation, or over a local TCP socket pair.

Completion critera for this work package:

 - [ ] extension of each mini-protocol's pipe test to run over multiplexing over a pipe, in isolation
 - [ ] run each mini-protocol's pipe test to run over multiplexing over a pipe, concurrently with ping-pong
 - [ ] run all mini-protocols together concurrently
